### ISSUE TITLE
Fresnel Problem

### ISSUE THREAD

**Issue by benjaminpope** [LouisDesdoigts/dLux#93] opened 2022-07-25 12:15 UTC
Hi @Jordan-Dennis,

I have been building docs for the Fresnel code in [a notebook here](https://github.com/LouisDesdoigts/dLux/blob/fresnel_doc/docs/notebooks/fresnel_defocus.ipynb), and I'm a little confused.

The 1D parameter inference of the HST focal length comes from a Fraunhofer model and comes out to 57.6 m - this is a bit too far! The units must be wrong here.

The `poppy` [Fresnel HST example](https://github.com/spacetelescope/poppy/blob/stable/notebooks/Fresnel_Propagation_Demo.ipynb) models the primary and then the secondary distance separately, and I don't know how to nicely do this in ∂Lux, so that would be cool to figure out. But more importantly, even taking a toy example of a Fresnel _out of focus_ PSF and inferring how far it is out of focus (see last cell in my example 10μm out of focus, you can get the plate scale from the header of the `poppy` PSF object) would be better - because then it proves we are doing Fresnel right!

**Comment by Jordan-Dennis** [comment] 2022-07-25 22:45
I have pushed the newest rendition of the code onto the `Fresnel` branch. The `FresnelExample.ipynb` is the one that you will want. I actually do a HST model there, just no inference. You will see that the phase is still not perfect as I am still in the process of hunting down the last bug. However, in general the PSFs are similar in form so I suspect that this issue is something to do with the `pixel_scale` or some other related parameter. 

Regards 

Jordan

**Comment by benjaminpope** [comment] 2022-07-26 06:51
Ok good - let me know when we have nailed it down and I will do the docs.

**Comment by Jordan-Dennis** [comment] 2022-07-30 22:27
Ok the fresnel algorithms are fully working. I will direct you to (this)[https://github.com/LouisDesdoigts/dLux/blob/Fresnel/dLux/dev/FresnelExample.ipynb] notebook on the `Fresnel` branch. I am just working on re-organising the files and completing the documentation and then I will open a pull request.

**Comment by benjaminpope** [comment] 2022-07-31 01:57
Awesome, this is great progress. It looks good!

Re your HST simulation the phases being different - I do notice that the main difference is sometimes having π instead of -π. I wonder if this is just a numerical precision issue - you could also try plotting the real and imaginary components?

**Comment by Jordan-Dennis** [comment] 2022-07-31 21:15
Yeah I wasn't too concerned with what was left over as residual, since it is fine detail in the aliasing (mostly). Do you think I should be?

**Comment by benjaminpope** [comment] 2022-07-31 22:34
I think it probably is just numerical position, as it seems to just be flipping -π to π in the image. It might be worth checking that, and checking that the amplitudes are all close. Checking the amplitudes are all close between poppy and dLux at a range of distances can be a unit test.

**Comment by LouisDesdoigts** [comment] 2022-08-01 01:25
Damn @Jordan-Dennis this is really really good, 😄 genuinely super stoked about this! This is a hard algorithm to Jaxify and you've absolutely nailed it, great stuff. Can't wait to start doing some hardcore calibration of Webb using this! 

Also the write up you've done in the notebook is really informative and I think it hits most of the sore-spots of working with Jax/Equinox/∂Lux. I think we should look into turning this into some docs or 'sharp-bits' notebook for people wanting to get started with ∂Lux if they're new to autodiff etc. LMK if you want to drive that, or we could work on it collaboratively too.

Re the phase differences: Yeah it looks like simple phase-wrapping caused by floating point precision. You should be able to characterize if this is the case by taking the remainder of the phase residual with pi. It's basically the same issue I was having with interpolation, hence to shift to storing amplitude and phase separately. As Ben said you could probably also check by taking the real and imaginary residuals. Or inspect the result by eye using a wrapping colorbar... There's a few ways to check before deep-diving into debug land, I'm pretty confident what you have here is correct.

Also is there a reason that the `GaussianPropagator` doesn't inherit from `FixedSamplingPropagator`? I had a brief look and as best I could tell `FixedSamplingPropagator` shifts and FT's in the single function, but you're applying the shift in the step in `_plane_to_plane`, `_waist_to_spherical`, `_spherical_to_waist`. I couldn't see anywhere that the shift isn't immediately applied, but there might a deeper reason. If not I think we should make it inherit from `FixedSamplingPropagator`, but this isn't super high-priority. I'm happy if you want to merge it in and then we can just make an issue and tackle it later, up to you really.

Final thing, did you have an attempt at replacing the FFT's with MFT's? Not the highest priority but definitely still something we want to do. Same as above, we can merge and make an issue. I think it actually shouldn't be too hard as long as the pixel scales are fully tracked throughout the propagation which it looks like they are (it all in Cartesian, not angular coordinates right?) . TBH it might just require me sitting down and playing around with the code for an arvo as I'm not sure how to derive the solution analytically for this more complex algorithm, it might require different equations for the different kind of propagations.

Either way super stoked about this dude 🤙🤙

**Comment by benjaminpope** [comment] 2022-08-01 03:23
Yes - agree with Louis, this is impressive to get a working Fresnel code going, there aren't that many around, let alone with autodiff and GPU support!

Re the notebook, I think we want a 

- [ ] streamlined one for a user docs notebook page,
- [ ] a set of unit tests doing the comparison (to `poppy` but also should we try `hcipy`?), and
- [ ] some of the sharp bits as a separate notebook.

MFTs will be good I think - we just need to propagate the coordinates correctly. This will be important if we do spherical non paraxial waves down the track.

**Comment by Jordan-Dennis** [comment] 2022-08-04 21:08
Ok cool. I will make some time of Saturday to finish this of then.

**Comment by Jordan-Dennis** [comment] 2022-09-14 22:22
@LouisDesdoigts, I understand you did some work on this I was just wondering where you got to?

**Comment by Jordan-Dennis** [comment] 2022-11-21 23:30
Following on from yesterdays meeting, the state of this is that there is a working FFT Fresnel algorithm. It runs in similar time to the `numpy` option from `poppy`. Shall this issue be used to discuss the MFT Fresnel that we have been considering or can it be closed (perhaps docs still need work)?

**Comment by LouisDesdoigts** [comment] 2023-10-04 04:11
Being re-worked in the background and is not currently part of the package, so closing this one.

**Closed by LouisDesdoigts** 2023-10-04 04:11 UTC
Labels: bug, documentation, help wanted
